---
- hosts: all
  sudo: yes
  gather_facts: no
  vars:
    deploy_user_password: deploy
    install_path: /usr/local/bin/lein # system wide install
    java_version: 7
    lein_script_path: https://raw.github.com/technomancy/leiningen/preview/bin/lein
  roles:
    - clojure
